### PR TITLE
optimize code

### PR DESCRIPTION
**Pull request by Hadock-is-ok**

### CODE REVIEW

**Comment by Hadock-is-ok** [comment]
lgtm

**Review by Hadock-is-ok — COMMENTED** [review]
lgtm

**Comment by du-cki** [comment]
Please update the README.md to reflect your changes, this is clearly a breaking change.

**Comment by Hadock-is-ok** [comment]
> Please update the README.md to reflect your changes, this is clearly a breaking change.

got it 2 secs

**Comment by Hadock-is-ok** [comment]
@itswilliboy i think it's ready to push, @du-cki?

**Comment by Hadock-is-ok** [comment]
CLOSING DUE TO INACTIVITY

**Pull request closed without merging**
