### PR TITLE
Chatgpt rewrite this project in rust

### PR DESCRIPTION
**Pull request by cyrus01337**
This is the greatest Discord bot of all time.

### CODE REVIEW

**Comment by itswilliboy** [comment]
i don't see any rust 🤨

**Comment by cyrus01337** [comment]
Coming in v3

**Comment by itswilliboy** [comment]
closing due to no rust

**Comment by cyrus01337** [comment]
The real villain.

**Review by Hadock-is-ok — APPROVED** [review]
LGTM push to prod

**Pull request closed without merging**
